// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cberrojynahjnplaezji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZXJyb2p5bmFoam5wbGFlemppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NTM1MTIsImV4cCI6MjA5MDEyOTUxMn0.VWBfMlvfuPrOG0ykmwg3Rn4E_yAUpETpmuY3LdfR_WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});